site_name: Guardiões da Saúde - MDS & REQ
repo_url: https://github.com/mdsreq-fga-unb/2022.1-GDS

theme:
    name: material
    language: pt
    features:
        - navigation.tabs
    palette:
        primary: teal
        accent: cyan

nav:
    - Home: index.md
    - Documentação:
          - Visão do produto e projeto: produto.md
          - Canvas: canvas.md
          - MVPs: MVPs.md
          - PBB: PBB.md
          - User Story Mapping: Us-Mapping.md
          - Dojo em React: dojo.md
          - Licoes Aprendidas: licoes_aprendidas.md
          - Reportes: report.md
          - Documento de Arquitetura: arquitetura.md
          - Identidade Visual: id_visual.md
          - Documentação dos Casos de Uso:
                - Criar Módulo: ./UCs/criar_modulo.md
                - Editar Módulo: ./UCs/editar_modulo.md
                - Reporte Semanal: ./UCs/reporte_semanal.md
                - Visualizar Métricas: ./UCs/visualizar_metricas.md
                - Visualizar Módulos disponíveis: ./UCs/visualizar_modulos.md
    - Entregas: entregas.md
